### ISSUE TITLE
#import "ATLAddressBarViewController.h" not found

### ISSUE THREAD

**Issue by Alkalouti** [layerhq/Atlas-iOS#1070]
My app support iOS 7
Using Atlas (1.0.11)
Using LayerKit (0.16.0)

Find Attached ..

![untitled](https://cloud.githubusercontent.com/assets/3541656/12035007/b7f6201a-ae40-11e5-87ec-7044616ab7ae.png)

i got this error

**Comment by mathmatrix828** [comment]
+1, using iOS 9 and cocoapods

**Comment by mathmatrix828** [comment]
@Alkalouti, after some research it appears this is an issue where the code is incompatible with Swift 2  - [referenced here](https://github.com/ashleymills/Reachability.swift/issues/21). As per #1074 Swift support has been requested. Not much else to do at the moment, unless you feel like writing the Swift libraries yourself

**Comment by Rupert-RR** [comment]
As a heads up in case people are still having this problem, I came across the same issue and following http://stackoverflow.com/questions/32668723/atladdressbarviewcontroller-h-not-found-in-atlas-h (and some other explanations), added `$(PODS_ROOT)` with the *recursive* option to *Search Paths* in the build settings for my target.

I suspect that this means that it is a CocoaPods integration problem — either CocoaPods should be setting this parameter and it isn't, or the Podspec is not properly configured (I don't know how to do Podspecs).

**Comment by ksylvest** [comment]
Able to reproduce this bug with the following:

`Xcode > File > New > Project...`

```ruby
use_frameworks!
platform :ios, '8.0'

target 'Example' do
  pod 'Atlas'
end
```

```bash
pod --version # 1.0.0.beta.5
pod install
```

Please fix this! It has been broken for almost three months.

**Comment by feifanzhou** [comment]
@ksylvest We are tracking [an issue](https://github.com/CocoaPods/CocoaPods/issues/4950#issuecomment-196289770) with Cocoapods >= 1.0.0b4. That exact setup should install/build fine on Cocoapods 0.39.x.

@Alkalouti @mathmatrix828 Does @Rupert-RR's link fix your build? If not, can you verify your Cocoapods version?

**Comment by mathmatrix828** [comment]
@feifanzhou I've moved away from Atlas at this point, and the project I was planning on using it for didn't pan out. I can fork and do some debugging in my spare time, but unfortunately that has been very limited of late

**Comment by kmahal** [comment]
Closing this issue, but we can re-open if it still exists.

**Comment by ksylvest** [comment]
Did it get fixed?

**Comment by feifanzhou** [comment]
@ksylvest we have not made any changes to specifically target CocoaPods >= 1.0.0b4, as it seems to be a breaking change on their end.

**Comment by Stakenborg** [comment]
I'm seeing this now with Cocoapods 1.0.0 officially released. Trying to find a workaround...

**Comment by mathmatrix828** [comment]
@Stakenborg as this is now a relevant issue, re-open and bump?

**Comment by mathmatrix828** [comment]
I'm willing to contribute if I can

**Comment by feifanzhou** [comment]
I'm willing to re-open. We likely won't be able to take a look for a while (backlogged a bit), but @mathmatrix828 would be glad to work with you in the meantime. There are a couple of reports of this issue, namely https://github.com/CocoaPods/CocoaPods/issues/5230. There are possible fixes here: https://github.com/CocoaPods/CocoaPods/issues/5197

**Comment by mathmatrix828** [comment]
@feifanzhou I'll clone and fork, try to put some time into it, and review those other issues. If I can get into contact with the Cocoapods managers for an assist on the new linking standards (seems like a linking issue?) I will. Until then, I'll try to push some stuff to my repo [here](https://github.com/mathmatrix828/Atlas-iOS) as I can. Anyone else please check my repo for updates and send all related issues here. When I think I've solved it I'll create a merge request, or if another method works better let me know

**Comment by feifanzhou** [comment]
@mathmatrix828 that sounds good. Make sure to update your Atlas fork; it's a decent number of commits behind :)

**Comment by mathmatrix828** [comment]
Already done (:

**Comment by kcoleman731** [comment]
@mathmatrix828 @Alkalouti  this ticket should be resolved as of #1191. Closing this ticket for now. Please let me know if you have any other issue.

**Comment by Stakenborg** [comment]
@kcoleman731 I'm still seeing this issue when I try to make a production archive. Seems fine if I just build and run though.

**Comment by feifanzhou** [comment]
@Stakenborg do you still run into the issue archiving after deleting Derived Data?

**Comment by Stakenborg** [comment]
@feifanzhou Yes, I tried deleting the derived data, clean, restarting Xcode, all the normal stuff. The odd thing is it will still build under a release configuration, but not archive.

**Comment by Stakenborg** [comment]
Actually now it's just happening on everything, I've tried uninstalling/reinstalling the pod, uninstalling/reinstalling cocoapods and the pod...no idea what is causing this.

**Comment by mathmatrix828** [comment]
Did you download my pull or the version from this repo?

**Comment by Stakenborg** [comment]
I'm doing a normal pod install, not specifying any repo for the podspec. Is it just an issue of the podspec hosted on Cocoapods not being updated yet?

**Comment by Stakenborg** [comment]
Seems to be the updated podspec that fixes this issue is not on the Cocoapods master podspec repo yet. I was able to fix this for the time being by specifying to use the Atlas git as the route to the podspec like this:
`pod 'Atlas', :git => 'https://github.com/layerhq/Atlas-iOS.git'`

However, this should definitely be up on the regular spec repo.

**Comment by mathmatrix828** [comment]
This issue is the original lib is being compiled against <v1.0.0 of CocoaPods. My pull request as stated above should fix this. I haven't had time to make some of the requested rollbacks yet but the build itself is clean
