### ISSUE TITLE
ATLConversationListViewController Crash on [tableView endUpdates]

### ISSUE THREAD

**Issue by immexerxez** [layerhq/Atlas-iOS#1116]
I`ve been having a lot of issues with this controller after adding a compound query predicate especially in the tableview reloading and the row animations. It also seems bogged down when the table starts getting too long and it will always crash after a clean install of the app on either endUpdates or reloadCellAtIndexPath. Any ideas of what could be the issue? everything besides the compound predicate is stock Atlas

**Comment by immexerxez** [comment]
Was using old version of layerkit

**Comment by immexerxez** [comment]
this issue still happens in queryController didChangeObjectAtIndex

**Comment by fysteven** [comment]
Yeah. I have the same issue, too.

Thread : Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x109bade4d (Missing)
1  libobjc.A.dylib                0x1075f9deb (Missing)
2  CoreFoundation                 0x109badcca (Missing)
3  Foundation                     0x104cb74de (Missing)
4  UIKit                          0x105a81dc6 (Missing)
5  Branch                         0x1030aa0da -[ATLConversationListViewController queryControllerDidChangeContent:] (ATLConversationListViewController.m:685)
6  Branch                         0x1033d1df2 -[LYRQueryController updateWithObjectIdentifiers:changedObjects:] (LYRQueryController.m:316)
7  libdispatch.dylib              0x10a5afd59 (Missing)
8  libdispatch.dylib              0x10a5cb4a7 (Missing)
9  libdispatch.dylib              0x10a5b5f2d (Missing)
10 CoreFoundation                 0x109b0dd09 (Missing)
11 CoreFoundation                 0x109acf2c9 (Missing)
12 CoreFoundation                 0x109ace828 (Missing)
13 GraphicsServices               0x10b8b4ad2 (Missing)
14 UIKit                          0x105956610 (Missing)
15 Branch                         0x1031370e1 main (main.m:14)
16 libdyld.dylib                  0x10a5fa92d (Missing)
17 (Missing)                      0x1 (Missing)

**Comment by fysteven** [comment]
Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of sections. The number of sections contained in the table view after the update (1) must be equal to the number of sections contained in the table view before the update (0), plus or minus the number of sections inserted or deleted (2 inserted, 0 deleted).

**Comment by burcsade** [comment]
Same here. It started happening after adding a query to check the number of unread conversations periodically.

Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of sections. The number of sections contained in the collection view after the update (1) must be equal to the number of sections contained in the collection view before the update (1), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).

```
0  CoreFoundation                 0x180fed900 __exceptionPreprocess
1  libobjc.A.dylib                0x18065bf80 objc_exception_throw
2  CoreFoundation                 0x180fed7d0 +[NSException raise:format:]
3  Foundation                     0x18196099c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKit                          0x18650af24 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:]
5  UIKit                          0x18650e640 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:]
6  UIKit                          0x18650e4bc -[UICollectionView _performBatchUpdates:completion:invalidationContext:]
7  UIKit                          0x185eceae8 -[UICollectionView performBatchUpdates:completion:]
8  app                      0x10016ec30  -[ATLConversationViewController queryControllerDidChangeContent:] (ATLConversationViewController.m:1210)
```

**Comment by JRam13** [comment]
Also having crash issues.

**Comment by burcsade** [comment]
Traced the issue back to the query controller in ATLConversationViewController. Here is how it happens:

- When conversation view controller is displayed, the fetchLayerMessages method creates the query controller and assigns itself as delegate to receive the changes.
- If this view controller is dismissed, the conversationDataSource is set to nil automatically but the query controller is still tracking changes and passes this information to its delegate.
- At this moment, if a new message is received, conversationDataSource.queryController triggers the delegate to update the collection view, but numberOfSectionsInCollectionView in ATLConversationViewController returns 0+1.

Here we end up with the following exception because there is a change in number of sections in query controller but numberOfSectionsInCollectionView returns the same value over and over.

Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of sections. The number of sections contained in the collection view after the update (1) must be equal to the number of sections contained in the collection view before the update (1), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).

The fix is unsetting the delegate so the query controller does not track changes when conversation view controller is dismissed. Updating the setConversation method in ATLConversationViewController fixes the issue.

```
- (void)setConversation:(LYRConversation *)conversation
{
    if (!conversation && !_conversation) return;
    if ([conversation isEqual:_conversation]) return;
    
    _conversation = conversation;
    
    self.showingMoreMessagesIndicator = NO;
    [self.typingParticipantIDs removeAllObjects];
    [self updateTypingIndicatorOverlay:NO];
    
    // Set up the controller for the conversation
    [self configureControllerForConversation];
    [self configureAddressBarForChangedParticipants];
    
    if (conversation) {
        [self fetchLayerMessages];
    } else {
	    // unset the query controller delegate here
        self.conversationDataSource.queryController.delegate = nil;
	
        self.conversationDataSource = nil;
        [self.collectionView reloadData];
    }
    CGSize contentSize = self.collectionView.collectionViewLayout.collectionViewContentSize;
    [self.collectionView setContentOffset:[self bottomOffsetForContentSize:contentSize] animated:NO];
}
```

Hope it helps!

**Comment by fysteven** [comment]
Hey, I got the same crash again. The previous solution doesn't seem to be working.

**Comment by kcoleman731** [comment]
Hi All, thanks for this issue and apologies for the delay in responding. @burcsade thanks for the explanation as well. Can you all tell me what versions of `Atlas` and `LayerKit` you are using?

We fixed the underlying `LayerKit` issue which generated a bunch of collection view animation crashes with https://github.com/layerhq/releases-ios/releases/tag/v0.19.2. If there are still crashes occurring with newer versions, I'll need to dig in.

**Comment by burcsade** [comment]
I was using LayerKit v0.19.4 and Atlas v1.0.19. 

I've updated to the latest version and the issue I've mentioned still exists in Atlas v1.0.22.

Thanks for the updates fixing other issues by the way!

**Comment by kcoleman731** [comment]
@burcsade no worries. with Atlas v1.0.22, does you fix solve this issue? If so, mind putting together a PR for it?

**Comment by burcsade** [comment]
@kcoleman731 Sure, created a PR.

**Comment by Spenser** [comment]
I am seeing this issue on Atlas v.1.0.30 has the issue resurfaced? I had previously had an older version and had never experienced the crash until upgrading to 1.0.30. @kcoleman731

**Comment by Spenser** [comment]
@kcoleman731 It looks like we are still having this same crash even on the 1.0.31. Have there been any fixes regarding this issue?

**Comment by Siemian** [comment]
We are also experiencing this issue with 1.0.32 version here is our stacktrace:
```
Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of sections. The number of sections contained in the collection view after the update (13) must be equal to the number of sections contained in the collection view before the update (13), plus or minus the number of sections inserted or deleted (4 inserted, 0 deleted).
Last Exception Backtrace:
0   CoreFoundation                	0x18e8c2fd8 __exceptionPreprocess + 124 (NSException.m:165)
1   libobjc.A.dylib               	0x18d324538 objc_exception_throw + 56 (objc-exception.mm:521)
2   CoreFoundation                	0x18e8c2eac +[NSException raise:format:arguments:] + 104 (NSException.m:131)
3   Foundation                    	0x18f35a710 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 112 (NSException.m:157)
4   UIKit                         	0x1952fc7cc -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 11640 (UICollectionView.m:5765)
5   UIKit                         	0x19530065c -[UICollectionView _endUpdatesWithInvalidationContext:tentativelyForReordering:animator:] + 92 (UICollectionView.m:6627)
6   UIKit                         	0x19530093c -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:] + 384 (UICollectionView.m:6685)
7   UIKit                         	0x19530079c -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 96 (UICollectionView.m:6649)
8   UIKit                         	0x195300720 -[UICollectionView _performBatchUpdates:completion:invalidationContext:] + 84 (UICollectionView.m:6644)
9   UIKit                         	0x194bc8558 -[UICollectionView performBatchUpdates:completion:] + 64 (UICollectionView.m:6633)
10  Atlas                         	0x100f2fc38 -[ATLConversationViewController queryControllerDidChangeContent:] + 684 (ATLConversationViewController.m:1252)
11  LayerKit                      	0x101532b5c 0x101418000 + 1157980
12  libdispatch.dylib             	0x18d77a9a0 _dispatch_client_callout + 16 (object.m:473)
13  libdispatch.dylib             	0x18d78b7a8 _dispatch_barrier_sync_f_slow_invoke + 304 (queue.c:3585)
14  libdispatch.dylib             	0x18d77a9a0 _dispatch_client_callout + 16 (object.m:473)
15  libdispatch.dylib             	0x18d77f5e8 _dispatch_main_queue_callback_4CF + 996 (inline_internal.h:2431)
16  CoreFoundation                	0x18e8710c0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12 (CFRunLoop.c:1793)
17  CoreFoundation                	0x18e86ecdc __CFRunLoopRun + 1572 (CFRunLoop.c:3004)
18  CoreFoundation                	0x18e79ed94 CFRunLoopRunSpecific + 424 (CFRunLoop.c:3113)
19  GraphicsServices              	0x190208074 GSEventRunModal + 100 (GSEvent.c:2245)
20  UIKit                         	0x194a57130 UIApplicationMain + 208 (UIApplication.m:4089)
21  App                     	0x1000daa58 main + 120 (AppDelegate.swift:21)
22  libdyld.dylib                 	0x18d7ad59c start + 4
```

**Comment by sara-shokry** [comment]
we also get about 53 crash on last 7 days because of this issue 
 Atlas (1.0.32) 
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x190742fe0 __exceptionPreprocess
1  libobjc.A.dylib                0x18f1a4538 objc_exception_throw
2  CoreFoundation                 0x190742eb4 +[NSException raise:format:]
3  Foundation                     0x1911da720 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKit                          0x19717e87c -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:]
5  UIKit                          0x19718270c -[UICollectionView _endUpdatesWithInvalidationContext:tentativelyForReordering:animator:]
6  UIKit                          0x1971829ec -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:]
7  UIKit                          0x19718284c -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:]
8  UIKit                          0x1971827d0 -[UICollectionView _performBatchUpdates:completion:invalidationContext:]
9  UIKit                          0x196a4a48c -[UICollectionView performBatchUpdates:completion:]
10 Atlas                          0x101c4bec4 -[ATLConversationViewController queryControllerDidChangeContent:] (ATLConversationViewController.m:1244)
11 LayerKit                       0x101e9e73c (Missing)
12 libdispatch.dylib              0x18f5fa9a0 _dispatch_client_callout
13 libdispatch.dylib              0x18f60b7a8 _dispatch_barrier_sync_f_slow_invoke
14 libdispatch.dylib              0x18f5fa9a0 _dispatch_client_callout
15 libdispatch.dylib              0x18f5ff5e8 _dispatch_main_queue_callback_4CF
16 CoreFoundation                 0x1906f10c8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
17 CoreFoundation                 0x1906eece4 __CFRunLoopRun
18 CoreFoundation                 0x19061eda4 CFRunLoopRunSpecific
19 GraphicsServices               0x192088074 GSEventRunModal
20 UIKit                          0x1968d9058 UIApplicationMain

**Comment by balrajOla** [comment]
```
(
    0   CoreFoundation                      0x000000010ba10b0b __exceptionPreprocess + 171
    1   libobjc.A.dylib                     0x000000010b47c141 objc_exception_throw + 48
    2   CoreFoundation                      0x000000010ba14cf2 +[NSException raise:format:arguments:] + 98
    3   Foundation                          0x000000010b0163b6 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
    4   UIKit                               0x000000010a03053d -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 15364
    5   UIKit                               0x000000010a039259 -[UICollectionView _endUpdatesWithInvalidationContext:tentativelyForReordering:animator:] + 71
    6   UIKit                               0x000000010a0395a0 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:] + 437
    7   UIKit                               0x000000010a0393c8 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 91
    8   UIKit                               0x000000010a03934a -[UICollectionView _performBatchUpdates:completion:invalidationContext:] + 74
    9   UIKit                               0x000000010a03929f -[UICollectionView performBatchUpdates:completion:] + 53
    10  Atlas                               0x0000000104ed30ce -[ATLConversationViewController queryControllerDidChangeContent:] + 1134
    11  LayerKit                            0x0000000106bb2b0a __76-[LYRQueryController updateWithObjectIdentifiers:changedObjectsIdentifiers:]_block_invoke.239 + 74
    12  libdispatch.dylib                   0x000000010cde905c _dispatch_client_callout + 8
    13  libdispatch.dylib                   0x000000010cdcc0f8 _dispatch_barrier_sync_f_slow_invoke + 579
    14  libdispatch.dylib                   0x000000010cde905c _dispatch_client_callout + 8
    15  libdispatch.dylib                   0x000000010cdca40b _dispatch_main_queue_callback_4CF + 411
    16  CoreFoundation                      0x000000010b9d5909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    17  CoreFoundation                      0x000000010b99bae4 __CFRunLoopRun + 2164
    18  CoreFoundation                      0x000000010b99b016 CFRunLoopRunSpecific + 406
    19  GraphicsServices                    0x000000010de41a24 GSEventRunModal + 62
    20  UIKit                               0x00000001096e50d4 UIApplicationMain + 159
    21  HDDoctor                            0x000000010439f797 main + 55
    22  libdyld.dylib                       0x00000001095c865d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Any solution to this crash??
